"""empty message

Revision ID: e98b9587ec39
Revises: 33b51816f7b4
Create Date: 2023-12-12 21:20:13.938545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e98b9587ec39'
down_revision = '33b51816f7b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venues')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_superadmin', sa.Boolean(), nullable=False))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('venue_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue_id', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'venues', ['venue_id'], ['id'])
        batch_op.drop_column('price')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('is_superadmin')

    op.create_table('venues',
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('createdAt', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###
